"""add system_prompt to ai_engine

Revision ID: 94bf980243a1
Revises: 
Create Date: 2026-04-13 18:24:30.817789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94bf980243a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_engines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_prompt', sa.Text(), server_default='', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_engines', schema=None) as batch_op:
        batch_op.drop_column('system_prompt')

    # ### end Alembic commands ###
