import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split('''
drv_sai_inmp441.c
audio_process.c
audio_capture_thread.c
''')

path = [cwd]

group = DefineGroup('SAI_INMP441', src, depend = [''], CPPPATH = path)

Return('group')
