import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split('''
uart_oled_thread.c
''')

path = [cwd]

group = DefineGroup('UART_OLED', src, depend = [''], CPPPATH = path)

Return('group')
